// All CopyRight by BooZaGameStudio // 


#include "FOR_COMMON/SECTION_TAG/Inventory/DZHotKeyTag.h"

namespace DZ
{
	namespace Inventory
	{
		UE_DEFINE_GAMEPLAY_TAG(DZ_INVNETORY_HOTKEY1,"DZ.Inventory.HotKey.1");
		UE_DEFINE_GAMEPLAY_TAG(DZ_INVNETORY_HOTKEY2,"DZ.Inventory.HotKey.2");
		UE_DEFINE_GAMEPLAY_TAG(DZ_INVNETORY_HOTKEY3,"DZ.Inventory.HotKey.3");
		UE_DEFINE_GAMEPLAY_TAG(DZ_INVNETORY_HOTKEY4,"DZ.Inventory.HotKey.4");
		UE_DEFINE_GAMEPLAY_TAG(DZ_INVNETORY_HOTKEY5,"DZ.Inventory.HotKey.5");
		UE_DEFINE_GAMEPLAY_TAG(DZ_INVNETORY_HOTKEY6,"DZ.Inventory.HotKey.6");
		UE_DEFINE_GAMEPLAY_TAG(DZ_INVNETORY_HOTKEY7,"DZ.Inventory.HotKey.7");
		UE_DEFINE_GAMEPLAY_TAG(DZ_INVNETORY_HOTKEY8,"DZ.Inventory.HotKey.8");
		UE_DEFINE_GAMEPLAY_TAG(DZ_INVNETORY_HOTKEY9,"DZ.Inventory.HotKey.9");
	}
}
