// All CopyRight by BooZaGameStudio // 


#include "FOR_COMMON/SECTION_TAG/GAS/GA/DZGATag.h"

namespace DZ
{
	namespace GA
	{
		UE_DEFINE_GAMEPLAY_TAG(DZ_GA_ANOMALY_EVENTTRIGGER, "DZ.GA.Anomaly.EventTrigger");
		UE_DEFINE_GAMEPLAY_TAG(DZ_GA_ANOMALY_BLOODDECAL, "DZ.GA.Anomaly.BloodDecal");
		UE_DEFINE_GAMEPLAY_TAG(DZ_GA_ANOMALY_BLOODFILL, "DZ.GA.Anomaly.BloodFill");
		UE_DEFINE_GAMEPLAY_TAG(DZ_GA_ANOMALY_FIRE, "DZ.GA.Anomaly.Fire");
		UE_DEFINE_GAMEPLAY_TAG(DZ_GA_ANOMALY_TRIGGERFIRE, "DZ.GA.Anomaly.TriggerFire");
		UE_DEFINE_GAMEPLAY_TAG(DZ_GA_ANOMALY_DROP, "DZ.GA.Anomaly.Drop");
		UE_DEFINE_GAMEPLAY_TAG(DZ_GA_ANOMALY_JUMP, "DZ.GA.Anomaly.Jump");
		
	}
}
