// All CopyRight by BooZaGameStudio // 

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

// 핫키 태그

namespace DZ
{
	namespace Inventory
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_INVNETORY_HOTKEY1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_INVNETORY_HOTKEY2);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_INVNETORY_HOTKEY3);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_INVNETORY_HOTKEY4);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_INVNETORY_HOTKEY5);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_INVNETORY_HOTKEY6);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_INVNETORY_HOTKEY7);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_INVNETORY_HOTKEY8);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_INVNETORY_HOTKEY9);
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_INVNETORY_DROP_ITEM);
	}
}
