;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="DZ.AI.Hear.Player",NewTagName="DZ.AI.Hear.PlayerSound")
+GameplayTagList=(Tag="DZ.AI",DevComment="ai only use")
+GameplayTagList=(Tag="DZ.AI.ClockTime",DevComment="")
+GameplayTagList=(Tag="DZ.AI.Hear.AnomalySound",DevComment="")
+GameplayTagList=(Tag="DZ.AI.Hear.DoorSound",DevComment="")
+GameplayTagList=(Tag="DZ.AI.Hear.ItemSound",DevComment="")
+GameplayTagList=(Tag="DZ.AI.Hear.PlayerSound",DevComment="")
+GameplayTagList=(Tag="DZ.AI.Hear.SomethingSound",DevComment="")
+GameplayTagList=(Tag="DZ.AI.See",DevComment="")
+GameplayTagList=(Tag="DZ.AI.See.ChangeTarget",DevComment="")
+GameplayTagList=(Tag="DZ.AI.See.LostTarget",DevComment="")
+GameplayTagList=(Tag="DZ.AI.See.SawTarget",DevComment="")
+GameplayTagList=(Tag="DZ.MSG.Voice.Send",DevComment="")

