// All CopyRight by BooZaGameStudio // 

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace DZ
{
	namespace GameplayCue
	{	
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_CUE_ANOMALY_NIAGARA);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_CUE_ANOMALY_DECAL);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_CUE_ANOMALY_MATERIAL);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_CUE_ANOMALY_IMPACTSOUND);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_CUE_ANOMALY_POTLOOPSOUND);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DZ_CUE_ANOMALY_MOTION);
		
	}
}
